/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/effect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_healthEffect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar empresa e admin */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login de usuário */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar tokens via refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar motoristas da empresa */
        get: operations["DriverController_list"];
        put?: never;
        /** Cadastrar motorista */
        post: operations["DriverController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar motorista */
        get: operations["DriverController_getById"];
        put?: never;
        post?: never;
        /** Desativar motorista (soft delete) */
        delete: operations["DriverController_deactivate"];
        options?: never;
        head?: never;
        /** Atualizar motorista */
        patch: operations["DriverController_update"];
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alunos da empresa */
        get: operations["StudentController_list"];
        put?: never;
        /** Cadastrar aluno */
        post: operations["StudentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar aluno */
        get: operations["StudentController_getById"];
        put?: never;
        post?: never;
        /** Desativar aluno (soft delete) */
        delete: operations["StudentController_deactivate"];
        options?: never;
        head?: never;
        /** Atualizar aluno */
        patch: operations["StudentController_update"];
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar nova viagem (OUTBOUND ou RETURN) */
        post: operations["TripController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Encerrar viagem ativa */
        patch: operations["TripController_end"];
        trace?: never;
    };
    "/api/v1/trips/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter viagem ativa do motorista */
        get: operations["TripController_getActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar alunos da viagem com status de embarque
         * @description Contrato declarado — implementação na Story 3.5a.
         */
        get: operations["TripController_getStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar rotas da empresa */
        get: operations["RoutingController_list"];
        put?: never;
        /** Criar rota de transporte */
        post: operations["RoutingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar minhas rotas (motorista ou aluno) */
        get: operations["RoutingController_getMyRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar rota */
        get: operations["RoutingController_getById"];
        put?: never;
        post?: never;
        /** Deletar rota (hard delete) */
        delete: operations["RoutingController_remove"];
        options?: never;
        head?: never;
        /** Atualizar rota (parcial) */
        patch: operations["RoutingController_update"];
        trace?: never;
    };
    "/api/v1/routes/{routeId}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alunos vinculados à rota */
        get: operations["RoutingController_listRouteStudents"];
        put?: never;
        /** Vincular aluno a rota */
        post: operations["RoutingController_assignStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desvincular aluno da rota */
        delete: operations["RoutingController_unassignStudent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar motoristas vinculados à rota */
        get: operations["RoutingController_listRouteDrivers"];
        put?: never;
        /** Vincular motorista a rota */
        post: operations["RoutingController_assignDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/drivers/{driverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desvincular motorista da rota */
        delete: operations["RoutingController_unassignDriver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar check-in de embarque de um aluno
         * @description Idempotência: mesma X-Idempotency-Key retorna o resultado anterior com 201, sem duplicar.
         */
        post: operations["BoardingController_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TypeLiteralClass: Record<string, never>;
        RefineClass: Record<string, never>;
        CreateTripDto: {
            /**
             * @description ID da rota
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            routeId: string;
            /**
             * @description Tipo de viagem: ida (OUTBOUND) ou volta (RETURN)
             * @enum {string}
             */
            type: "OUTBOUND" | "RETURN";
            /**
             * @description ID da viagem de ida (obrigatório para RETURN)
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            relatedTripId?: string;
        };
        TripStudentItemDto: {
            /**
             * @description ID do aluno
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * @description Nome do aluno
             * @example Maria Silva
             */
            name: string;
            /**
             * @description Status de embarque do aluno na viagem
             * @example NOT_CHECKED_IN
             * @enum {string}
             */
            status: "CHECKED_IN" | "NOT_CHECKED_IN" | "NOT_RETURNING";
            /**
             * @description Data e hora do check-in (ISO 8601 UTC), null se ainda não embarcou
             * @example 2026-07-12T21:10:00.000Z
             */
            checkedInAt: string | null;
        };
        BoardingSummaryDto: {
            /**
             * @description Quantidade de alunos já embarcados
             * @example 12
             */
            boarded: number;
            /**
             * @description Quantidade total de alunos na viagem
             * @example 20
             */
            total: number;
        };
        TripStudentsResponseDto: {
            /** @description Lista de alunos da viagem com status de embarque */
            students: components["schemas"]["TripStudentItemDto"][];
            /** @description Resumo agregado de embarque — sempre calculado no servidor */
            summary: components["schemas"]["BoardingSummaryDto"];
        };
        ErrorBodyDto: {
            /**
             * @description Código de erro tipado
             * @example TRIP_NOT_ACTIVE
             */
            code: string;
            /**
             * @description Mensagem legível descrevendo o erro
             * @example A viagem não está ativa
             */
            message: string;
            /** @description Detalhes adicionais do erro (opcional) */
            details?: Record<string, never>;
        };
        ErrorResponseDto: {
            error: components["schemas"]["ErrorBodyDto"];
        };
        /** @description Payload do QR code exibido na tela do aluno (Story 3.2b) e decodificado pelo app do motorista (Story 3.3b). Codificação: string JSON compacta em UTF-8, gravada direto no QR, SEM base64 — QR menor para leitura mais rápida em movimento (NFR1). Não aparece em nenhum request/response HTTP: registrado no OpenAPI via @ApiExtraModels. */
        QrCodePayloadDto: {
            /**
             * Format: uuid
             * @description ID do aluno dono do QR code
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description UUID v4 gerado no cliente a cada login e persistido em MMKV — torna o QR estático por sessão (NFR8). O backend trata como opaco no MVP.
             * @example 550e8400-e29b-41d4-a716-446655440003
             */
            sessionId: string;
        };
        CheckInResponseDto: {
            /**
             * Format: uuid
             * @description ID do registro de check-in
             * @example 550e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * Format: uuid
             * @description ID do aluno que fez check-in
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem em que o check-in ocorreu
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Data e hora do check-in (ISO 8601 UTC)
             * @example 2026-07-12T21:10:00.000Z
             */
            checkedInAt: string;
            /**
             * @description Status do check-in
             * @example CHECKED_IN
             * @enum {string}
             */
            status: "CHECKED_IN";
        };
        CheckInRequestDto: {
            /**
             * Format: uuid
             * @description ID do aluno decodificado do QR code
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem ativa em que o check-in ocorre
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Momento real do embarque (ISO 8601 UTC), informado pela fila offline quando o check-in ocorreu sem sinal. Ausente ⇒ o servidor carimba o horário de processamento. Rejeitado com INVALID_QR_CODE se estiver no futuro (além da tolerância de relógio) ou mais de 24h no passado.
             * @example 2026-08-14T07:05:00.000Z
             */
            occurredAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_healthEffect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Empresa e admin criados com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais inválidas (INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Tokens renovados com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body inválido (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token inválido (INVALID_REFRESH_TOKEN) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_list: {
        parameters: {
            query?: {
                /** @description Filtrar por status ativo/inativo */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de motoristas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valor inválido para isActive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Motorista criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do motorista */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Motorista desativado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Motorista atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_list: {
        parameters: {
            query?: {
                /** @description Filtrar por status ativo/inativo */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valor inválido para isActive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Aluno criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do aluno */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aluno desativado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Aluno atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripDto"];
            };
        };
        responses: {
            /** @description Viagem criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente motoristas */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista já possui viagem ativa */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_end: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viagem encerrada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Viagem não está ativa */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Viagem não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_getActive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viagem ativa ou null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_getStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da viagem */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos da viagem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TripStudentsResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Acesso negado — somente motoristas */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description NOT_IMPLEMENTED — contrato declarado, implementação na Story 3.5a */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    RoutingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de rotas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Rota criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_getMyRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotas do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente DRIVER ou STUDENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rota deletada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Rota atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou body vazio (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_listRouteStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_assignStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Aluno vinculado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota ou aluno não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo já existe (ASSIGNMENT_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_unassignStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo não encontrado (ASSIGNMENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_listRouteDrivers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de motoristas da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_assignDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Motorista vinculado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota ou motorista não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo já existe (ASSIGNMENT_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_unassignDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
                driverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo não encontrado (ASSIGNMENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoardingController_checkIn: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID v4 gerado no cliente — chave da fila offline (Architecture §5, Tier 2). Mesma key reenviada retorna o mesmo resultado sem duplicar o check-in. */
                "X-Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequestDto"];
            };
        };
        responses: {
            /** @description Check-in registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CheckInResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description INVALID_QR_CODE — studentId ou tripId ausente/malformado, ou occurredAt fora da janela aceita (no futuro além da tolerância de relógio, ou mais de 24h no passado). O QR bruto nunca trafega (o app do motorista decodifica e envia campos estruturados), então este erro é validação de shape do body, não do QR em si. MISSING_IDEMPOTENCY_KEY — header X-Idempotency-Key ausente ou vazio (é required). INVALID_IDEMPOTENCY_KEY — header presente mas acima do limite de tamanho. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ALLOWED — aluno inexistente, inativo, de outra empresa ou não vinculado à rota da viagem. DRIVER_NOT_ASSIGNED — motorista autenticado não é o responsável por esta viagem. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. DUPLICATE_CHECK_IN — aluno já embarcou nesta viagem (key diferente). IDEMPOTENCY_KEY_CONFLICT — key já usada para um aluno ou viagem diferente do enviado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
