/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/effect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_healthEffect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar empresa e admin */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login de usuário */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar tokens via refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar motoristas da empresa */
        get: operations["DriverController_list"];
        put?: never;
        /** Cadastrar motorista */
        post: operations["DriverController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar motorista */
        get: operations["DriverController_getById"];
        put?: never;
        post?: never;
        /** Desativar motorista (soft delete) */
        delete: operations["DriverController_deactivate"];
        options?: never;
        head?: never;
        /** Atualizar motorista */
        patch: operations["DriverController_update"];
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alunos da empresa */
        get: operations["StudentController_list"];
        put?: never;
        /** Cadastrar aluno */
        post: operations["StudentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar aluno */
        get: operations["StudentController_getById"];
        put?: never;
        post?: never;
        /** Desativar aluno (soft delete) */
        delete: operations["StudentController_deactivate"];
        options?: never;
        head?: never;
        /** Atualizar aluno */
        patch: operations["StudentController_update"];
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar nova viagem (OUTBOUND ou RETURN) */
        post: operations["TripController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Encerrar viagem ativa */
        patch: operations["TripController_end"];
        trace?: never;
    };
    "/api/v1/trips/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter viagem ativa (motorista) ou retorno ativo do aluno
         * @description Para DRIVER: a viagem ativa do motorista autenticado. Para STUDENT: a viagem de retorno ativa na rota do aluno autenticado, para alimentar o aviso "Não vou voltar". Ambos retornam { data: null } quando não há viagem.
         */
        get: operations["TripController_getActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alunos da viagem com status de embarque */
        get: operations["TripController_getStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar rotas da empresa */
        get: operations["RoutingController_list"];
        put?: never;
        /** Criar rota de transporte */
        post: operations["RoutingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar minhas rotas (motorista ou aluno) */
        get: operations["RoutingController_getMyRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar rota */
        get: operations["RoutingController_getById"];
        put?: never;
        post?: never;
        /** Deletar rota (hard delete) */
        delete: operations["RoutingController_remove"];
        options?: never;
        head?: never;
        /** Atualizar rota (parcial) */
        patch: operations["RoutingController_update"];
        trace?: never;
    };
    "/api/v1/routes/{routeId}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alunos vinculados à rota */
        get: operations["RoutingController_listRouteStudents"];
        put?: never;
        /** Vincular aluno a rota */
        post: operations["RoutingController_assignStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desvincular aluno da rota */
        delete: operations["RoutingController_unassignStudent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar motoristas vinculados à rota */
        get: operations["RoutingController_listRouteDrivers"];
        put?: never;
        /** Vincular motorista a rota */
        post: operations["RoutingController_assignDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{routeId}/drivers/{driverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desvincular motorista da rota */
        delete: operations["RoutingController_unassignDriver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar check-in de embarque de um aluno
         * @description Idempotência: mesma X-Idempotency-Key retorna o resultado anterior com 201, sem duplicar.
         */
        post: operations["BoardingController_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/not-returning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar ausência "não vou voltar"
         * @description O aluno autenticado (studentId do JWT) avisa que não vai voltar na viagem ativa. Idempotência: mesma X-Idempotency-Key retorna o mesmo resultado com 201, sem duplicar. cancellableUntil (janela de cancelamento) é calculado pelo servidor — o cliente nunca calcula, só exibe o countdown.
         */
        post: operations["BoardingController_notReturning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/cancel-absence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar ausência dentro da janela de segurança
         * @description O aluno autenticado (studentId do JWT) desfaz a ausência registrada. Só é aceito dentro da janela cancellableUntil (notifiedAt + 2 minutos, calculada pelo servidor). Idempotência: mesma X-Idempotency-Key retorna o mesmo resultado com 200.
         */
        post: operations["BoardingController_cancelAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lembrete pendente de check-in na volta
         * @description Deriva na leitura o lembrete disparado pelo scan automático (Story 4.4) para o aluno autenticado (studentId do JWT): pendente somente se a linha BoardingReminder existe E o aluno ainda não fez check-in na viagem E não tem ausência ativa. 200 sempre — data null significa "sem lembrete" (sem viagem de retorno ativa, sem linha, ou pendência já resolvida). Permite quem não estava conectado ao stream ver o lembrete ao abrir o app.
         */
        get: operations["BoardingController_reminder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boarding/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream SSE de eventos de embarque da viagem do motorista
         * @description Canal em tempo real do motorista para a viagem ativa. Cada mensagem do stream traz a linha `event:` com o tipo (boarding.not_returning | boarding.absence_cancelled | boarding.checkin_reminder) e a linha `data:` com o payload JSON. A conexão é encerrada elegantemente quando a viagem termina; a reconexão após queda de rede é responsabilidade do cliente (EventSource), sem duplicar entradas na lista.
         */
        get: operations["BoardingController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracking/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transmitir a posição GPS do ônibus na viagem ativa
         * @description Recepção da posição capturada pelo device do motorista (envio automático enquanto a viagem está ativa). Last-write-wins: cada posição substitui a anterior e posições velhas são descartáveis — por isso NÃO usa X-Idempotency-Key (divergência consciente dos POSTs do boarding, que protegem operações na fila offline).
         */
        post: operations["TrackingController_ingestLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracking/trips/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Viagem ativa na rota do aluno para acompanhamento em tempo real
         * @description Descoberta da viagem a acompanhar (Story 5.2): a viagem ativa de QUALQUER perna (ida ou volta) em alguma rota do aluno — diferente de GET /trips/active, cuja branch STUDENT devolve só a viagem de retorno (semântica do "Não vou voltar"). A autorização é a própria query: aluno fora de rota ou sem viagem ativa recebe { data: null }, nunca 403 de negócio. Sem viagem, o cliente repete a consulta; quando o motorista inicia a viagem, a tela se reengaja sozinha.
         */
        get: operations["TrackingController_activeTrackingTrip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracking/trips/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Última posição conhecida do ônibus na viagem
         * @description Estado inicial da tela de acompanhamento antes do primeiro evento do stream e o que permanece visível quando o sinal GPS cai. Sem replay/Last-Event-ID no stream — o resync do aluno é este endpoint. A posição não é persistida em PostgreSQL: vive em cache com TTL curto, e a expiração é 404, nunca ponto stale.
         */
        get: operations["TrackingController_lastKnownLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracking/trips/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream SSE do acompanhamento do ônibus em tempo real
         * @description Canal em tempo real do aluno para a viagem: cada mensagem traz a linha `event:` com `location.updated` e a linha `data:` com a posição publicada. Sem replay/Last-Event-ID — após queda de rede, o resync é o GET .../location e a reconexão é responsabilidade do cliente (EventSource com backoff). A conexão é encerrada elegantemente quando a viagem termina. Auth via header Authorization (o token nunca vai na URL).
         */
        get: operations["TrackingController_tripLocationStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TypeLiteralClass: Record<string, never>;
        RefineClass: Record<string, never>;
        CreateTripDto: {
            /**
             * @description ID da rota
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            routeId: string;
            /**
             * @description Tipo de viagem: ida (OUTBOUND) ou volta (RETURN)
             * @enum {string}
             */
            type: "OUTBOUND" | "RETURN";
            /**
             * @description ID da viagem de ida (obrigatório para RETURN)
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            relatedTripId?: string;
        };
        ErrorBodyDto: {
            /**
             * @description Código de erro tipado
             * @example TRIP_NOT_ACTIVE
             */
            code: string;
            /**
             * @description Mensagem legível descrevendo o erro
             * @example A viagem não está ativa
             */
            message: string;
            /** @description Detalhes adicionais do erro (opcional) */
            details?: Record<string, never>;
        };
        ErrorResponseDto: {
            error: components["schemas"]["ErrorBodyDto"];
        };
        TripStudentItemDto: {
            /**
             * @description ID do aluno
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * @description Nome do aluno
             * @example Maria Silva
             */
            name: string;
            /**
             * @description Status de embarque do aluno na viagem
             * @example NOT_CHECKED_IN
             * @enum {string}
             */
            status: "CHECKED_IN" | "NOT_CHECKED_IN" | "NOT_RETURNING";
            /**
             * @description Data e hora do check-in (ISO 8601 UTC), null se ainda não embarcou
             * @example 2026-07-12T21:10:00.000Z
             */
            checkedInAt: string | null;
        };
        BoardingSummaryDto: {
            /**
             * @description Quantidade de alunos já embarcados
             * @example 12
             */
            boarded: number;
            /**
             * @description Quantidade total de alunos na viagem
             * @example 20
             */
            total: number;
        };
        TripStudentsResponseDto: {
            /** @description Lista de alunos da viagem com status de embarque */
            students: components["schemas"]["TripStudentItemDto"][];
            /** @description Resumo agregado de embarque — sempre calculado no servidor */
            summary: components["schemas"]["BoardingSummaryDto"];
        };
        /** @description Payload do QR code exibido na tela do aluno (Story 3.2b) e decodificado pelo app do motorista (Story 3.3b). Codificação: string JSON compacta em UTF-8, gravada direto no QR, SEM base64 — QR menor para leitura mais rápida em movimento (NFR1). Não aparece em nenhum request/response HTTP: registrado no OpenAPI via @ApiExtraModels. */
        QrCodePayloadDto: {
            /**
             * Format: uuid
             * @description ID do aluno dono do QR code
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description UUID v4 gerado no cliente a cada login e persistido em MMKV — torna o QR estático por sessão (NFR8). O backend trata como opaco no MVP.
             * @example 550e8400-e29b-41d4-a716-446655440003
             */
            sessionId: string;
        };
        CheckInResponseDto: {
            /**
             * Format: uuid
             * @description ID do registro de check-in
             * @example 550e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * Format: uuid
             * @description ID do aluno que fez check-in
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem em que o check-in ocorreu
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Data e hora do check-in (ISO 8601 UTC)
             * @example 2026-07-12T21:10:00.000Z
             */
            checkedInAt: string;
            /**
             * @description Status do check-in
             * @example CHECKED_IN
             * @enum {string}
             */
            status: "CHECKED_IN";
        };
        CheckInRequestDto: {
            /**
             * Format: uuid
             * @description ID do aluno decodificado do QR code
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem ativa em que o check-in ocorre
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Momento real do embarque (ISO 8601 UTC), informado pela fila offline quando o check-in ocorreu sem sinal. Ausente ⇒ o servidor carimba o horário de processamento. Rejeitado com INVALID_QR_CODE se estiver no futuro (além da tolerância de relógio) ou mais de 24h no passado.
             * @example 2026-08-14T07:05:00.000Z
             */
            occurredAt?: string;
        };
        NotReturningResponseDto: {
            /**
             * Format: uuid
             * @description ID do registro de ausência
             * @example 550e8400-e29b-41d4-a716-446655440004
             */
            id: string;
            /**
             * Format: uuid
             * @description ID do aluno que registrou a ausência (vem do JWT, nunca do body)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem em que a ausência foi registrada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Status do aluno após o registro da ausência
             * @example NOT_RETURNING
             * @enum {string}
             */
            status: "NOT_RETURNING";
            /**
             * @description Momento do registro da ausência (ISO 8601 UTC). Base do cálculo de cancellableUntil.
             * @example 2026-09-07T21:10:00.000Z
             */
            notifiedAt: string;
            /**
             * @description Fim da janela de cancelamento (ISO 8601 UTC), calculado pelo servidor como notifiedAt + 2 minutos. O cliente nunca calcula a janela — só exibe o countdown e esconde o cancelamento quando expira.
             * @example 2026-09-07T21:12:00.000Z
             */
            cancellableUntil: string;
        };
        NotReturningRequestDto: {
            /**
             * Format: uuid
             * @description ID da viagem ativa em que o aluno registra a ausência
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
        };
        CancelAbsenceResponseDto: {
            /**
             * Format: uuid
             * @description ID do aluno que cancelou a ausência (vem do JWT, nunca do body)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * Format: uuid
             * @description ID da viagem em que a ausência foi cancelada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Status do aluno após o cancelamento — volta a aguardar check-in
             * @example NOT_CHECKED_IN
             * @enum {string}
             */
            status: "NOT_CHECKED_IN";
            /**
             * @description Momento do cancelamento (ISO 8601 UTC)
             * @example 2026-09-07T21:11:00.000Z
             */
            cancelledAt: string;
        };
        CancelAbsenceRequestDto: {
            /**
             * Format: uuid
             * @description ID da viagem em que a ausência será cancelada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
        };
        PendingReminderResponseDto: {
            /**
             * Format: uuid
             * @description ID da viagem de retorno com lembrete pendente
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Momento do disparo do lembrete (ISO 8601 UTC) — o mesmo remindedAt do evento boarding.checkin_reminder
             * @example 2026-09-07T22:15:00.000Z
             */
            remindedAt: string;
        };
        /** @description Evento SSE `boarding.not_returning`: a linha `event:` do stream carrega este nome e a linha `data:` o payload JSON abaixo. Emitido ao motorista da viagem quando um aluno registra ausência (POST /not-returning, Story 4.1) — o status na lista muda para "NÃO VAI VOLTAR" e a contagem resumida se ajusta. O nome do aluno é resolvido pelo cliente a partir do roster. */
        BoardingNotReturningEventDto: {
            /**
             * Format: uuid
             * @description ID da viagem em que a ausência foi registrada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * Format: uuid
             * @description ID do aluno que registrou a ausência
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * @description Momento do registro da ausência (ISO 8601 UTC) — eco do notifiedAt da ausência
             * @example 2026-09-07T21:10:00.000Z
             */
            notifiedAt: string;
        };
        /** @description Evento SSE `boarding.absence_cancelled`: a linha `event:` do stream carrega este nome e a linha `data:` o payload JSON abaixo. Emitido ao motorista da viagem quando o aluno cancela a ausência dentro da janela (POST /cancel-absence, Story 4.3) — status e contagem resumida voltam ao estado anterior. O nome do aluno é resolvido pelo cliente a partir do roster. */
        BoardingAbsenceCancelledEventDto: {
            /**
             * Format: uuid
             * @description ID da viagem em que a ausência foi cancelada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * Format: uuid
             * @description ID do aluno que cancelou a ausência
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * @description Momento do cancelamento (ISO 8601 UTC) — eco do cancelledAt do cancelamento
             * @example 2026-09-07T21:11:00.000Z
             */
            cancelledAt: string;
        };
        /** @description Evento SSE `boarding.checkin_reminder`: a linha `event:` do stream carrega este nome e a linha `data:` o payload JSON abaixo. Lembrete in-app ao aluno que embarcou na ida e, após 15 minutos do início da viagem de retorno, não fez check-in nem registrou ausência (Story 4.4) — emitido no máximo uma vez por aluno por viagem. O nome do aluno é resolvido pelo cliente a partir do roster. A entrega ao aluno é derivada do estado na abertura do app (Story 4.4) — este stream é o canal do motorista. */
        BoardingCheckinReminderEventDto: {
            /**
             * Format: uuid
             * @description ID da viagem de retorno em curso
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * Format: uuid
             * @description ID do aluno que deve ser lembrado do check-in
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            studentId: string;
            /**
             * @description Momento do disparo do lembrete (ISO 8601 UTC)
             * @example 2026-09-07T22:15:00.000Z
             */
            remindedAt: string;
        };
        LocationIngestResponseDto: {
            /**
             * Format: uuid
             * @description ID da viagem cuja posição foi recebida
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Instante do recebimento da posição pelo servidor (ISO 8601 UTC) — last-write-wins: cada posição recebida substitui a anterior, sem acumular histórico
             * @example 2026-09-11T12:00:00.100Z
             */
            receivedAt: string;
        };
        LocationIngestRequestDto: {
            /**
             * Format: uuid
             * @description ID da viagem ativa em que a posição foi capturada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Latitude da posição em graus WGS84
             * @example -20.755549
             */
            latitude: number;
            /**
             * @description Longitude da posição em graus WGS84
             * @example -42.881728
             */
            longitude: number;
            /**
             * @description Precisão da leitura em metros (accuracy da Geolocation API). Opcional: o browser pode não fornecer o valor.
             * @example 12.5
             */
            accuracy?: number;
            /**
             * @description Instante da captura da posição pelo device (ISO 8601 UTC, com qualquer precisão fracionária — 0 a N casas). Não volta em nenhuma resposta do servidor: o ack carrega o receivedAt e o evento do stream carrega o timestamp de publicação.
             * @example 2026-09-11T12:00:00.000Z
             */
            capturedAt: string;
        };
        ActiveTrackingTripDto: {
            /**
             * Format: uuid
             * @description ID da viagem ativa na rota do aluno — alimenta o stream e o last-known
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Perna da viagem ativa (ida ou volta) — o acompanhamento serve às duas
             * @example OUTBOUND
             * @enum {string}
             */
            type: "OUTBOUND" | "RETURN";
        };
        LastKnownLocationDto: {
            /**
             * Format: uuid
             * @description ID da viagem a que a posição pertence
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Latitude do último ponto conhecido em graus WGS84
             * @example -20.755549
             */
            latitude: number;
            /**
             * @description Longitude do último ponto conhecido em graus WGS84
             * @example -42.881728
             */
            longitude: number;
            /**
             * @description Precisão da leitura em metros (accuracy da Geolocation API). Opcional: o browser pode não fornecer o valor.
             * @example 12.5
             */
            accuracy?: number;
            /**
             * @description Instante da captura da posição pelo device (ISO 8601 UTC, precisão fracionária ilimitada), ecoado sem alteração — o servidor nunca o compara com relógio algum. O estado degradado "Sem sinal GPS" da tela é avaliado pela RECEPÇÃO de dados no cliente (timer de 15s sem chegar posição nova: evento location.updated ou resposta deste endpoint), não pela idade deste campo — capturado há pouco não significa sinal vivo. Se a posição foi expirada (TTL do cache), o endpoint responde 404 NO_LOCATION_AVAILABLE, nunca um ponto stale.
             * @example 2026-09-11T12:00:00.000Z
             */
            capturedAt: string;
        };
        /**
         * @description Evento SSE `location.updated`: a linha `event:` do stream carrega este nome e a linha `data:` o payload JSON abaixo. Emitido aos alunos da rota a cada posição publicada pelo motorista da viagem ativa (Story 5.1). `timestamp` é o instante de publicação pelo servidor — o `capturedAt` do device só aparece no POST de ingestão e no last-known. Frame no wire:
         *     event: location.updated
         *     data: {"tripId":"550e8400-e29b-41d4-a716-446655440001","latitude":-20.755549,"longitude":-42.881728,"accuracy":12.5,"timestamp":"2026-09-11T12:00:00.150Z"}
         */
        LocationUpdatedEventDto: {
            /**
             * Format: uuid
             * @description ID da viagem em que a posição foi publicada
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            tripId: string;
            /**
             * @description Latitude da posição em graus WGS84
             * @example -20.755549
             */
            latitude: number;
            /**
             * @description Longitude da posição em graus WGS84
             * @example -42.881728
             */
            longitude: number;
            /**
             * @description Precisão da leitura em metros (accuracy da Geolocation API). Opcional: o browser pode não fornecer o valor.
             * @example 12.5
             */
            accuracy?: number;
            /**
             * @description Instante da publicação do evento pelo servidor (ISO 8601 UTC) — nunca o capturedAt do device
             * @example 2026-09-11T12:00:00.150Z
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_healthEffect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Empresa e admin criados com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais inválidas (INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Tokens renovados com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body inválido (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token inválido (INVALID_REFRESH_TOKEN) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_list: {
        parameters: {
            query?: {
                /** @description Filtrar por status ativo/inativo */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de motoristas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valor inválido para isActive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Motorista criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do motorista */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Motorista desativado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriverController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Motorista atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motorista não encontrado (DRIVER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_list: {
        parameters: {
            query?: {
                /** @description Filtrar por status ativo/inativo */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valor inválido para isActive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Aluno criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do aluno */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aluno desativado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Aluno atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aluno não encontrado (STUDENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email já cadastrado (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripDto"];
            };
        };
        responses: {
            /** @description Viagem criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN (role diferente de DRIVER) ou DRIVER_NOT_ASSIGNED (motorista não está vinculado a esta rota) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Motorista já possui viagem ativa */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_end: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viagem encerrada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Viagem não está ativa */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN (role diferente de DRIVER) ou DRIVER_NOT_ASSIGNED (motorista não é o responsável pela viagem) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Viagem não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TripController_getActive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viagem ativa ou null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN — somente motoristas e alunos (ADMIN não consulta) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TripController_getStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da viagem */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos da viagem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TripStudentsResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN (role diferente de DRIVER) ou DRIVER_NOT_ASSIGNED (motorista não é o responsável pela viagem) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    RoutingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de rotas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Rota criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_getMyRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotas do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente DRIVER ou STUDENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rota deletada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineClass"];
            };
        };
        responses: {
            /** @description Rota atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou body vazio (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota não encontrada (ROUTE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_listRouteStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de alunos da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_assignStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Aluno vinculado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota ou aluno não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo já existe (ASSIGNMENT_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_unassignStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo não encontrado (ASSIGNMENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_listRouteDrivers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de motoristas da rota */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_assignDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeLiteralClass"];
            };
        };
        responses: {
            /** @description Motorista vinculado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rota ou motorista não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo já existe (ASSIGNMENT_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutingController_unassignDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
                driverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID inválido (não-UUID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado — somente ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vínculo não encontrado (ASSIGNMENT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoardingController_checkIn: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID v4 gerado no cliente — chave da fila offline (Architecture §5, Tier 2). Mesma key reenviada retorna o mesmo resultado sem duplicar o check-in. */
                "X-Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequestDto"];
            };
        };
        responses: {
            /** @description Check-in registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CheckInResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description INVALID_QR_CODE — studentId ou tripId ausente/malformado, ou occurredAt fora da janela aceita (no futuro além da tolerância de relógio, ou mais de 24h no passado). O QR bruto nunca trafega (o app do motorista decodifica e envia campos estruturados), então este erro é validação de shape do body, não do QR em si. MISSING_IDEMPOTENCY_KEY — header X-Idempotency-Key ausente ou vazio (é required). INVALID_IDEMPOTENCY_KEY — header presente mas acima do limite de tamanho. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ALLOWED — aluno inexistente, inativo, de outra empresa ou não vinculado à rota da viagem. DRIVER_NOT_ASSIGNED — motorista autenticado não é o responsável por esta viagem. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. DUPLICATE_CHECK_IN — aluno já embarcou nesta viagem (key diferente). IDEMPOTENCY_KEY_CONFLICT — key já usada para um aluno ou viagem diferente do enviado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    BoardingController_notReturning: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID v4 gerado no cliente — chave da fila offline (Architecture §5, Tier 2, operação notify_not_returning). Mesma key reenviada retorna o mesmo resultado sem duplicar a ausência. */
                "X-Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotReturningRequestDto"];
            };
        };
        responses: {
            /** @description Ausência registrada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotReturningResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description VALIDATION_ERROR — body malformado (tripId ausente ou não é UUID). MISSING_IDEMPOTENCY_KEY — header X-Idempotency-Key ausente ou vazio (é required). INVALID_IDEMPOTENCY_KEY — header presente mas acima de 200 caracteres. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ON_TRIP — aluno não pertence à rota da viagem. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. ALREADY_NOT_RETURNING — ausência já registrada nesta viagem (key diferente). ALREADY_CHECKED_IN — aluno já embarcou nesta viagem: o check-in do motorista presente tem autoridade sobre a ausência, e o aluno deve falar com o motorista. IDEMPOTENCY_KEY_CONFLICT — key já usada para uma viagem diferente do enviado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    BoardingController_cancelAbsence: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID v4 gerado no cliente — chave da fila offline (Architecture §5, Tier 2, operação cancel_absence). Mesma key reenviada retorna o mesmo resultado. */
                "X-Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelAbsenceRequestDto"];
            };
        };
        responses: {
            /** @description Ausência cancelada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CancelAbsenceResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description VALIDATION_ERROR — body malformado (tripId ausente ou não é UUID). MISSING_IDEMPOTENCY_KEY — header X-Idempotency-Key ausente ou vazio (é required). INVALID_IDEMPOTENCY_KEY — header presente mas acima de 200 caracteres. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ON_TRIP — aluno não pertence à rota da viagem. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description ABSENCE_NOT_FOUND — ausência inexistente ou já cancelada, enviada com X-Idempotency-Key diferente. Reenvio da MESMA key da chamada original retorna o resultado original com 200. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. CANCELLATION_PERIOD_EXPIRED — fora da janela cancellableUntil (notifiedAt + 2 minutos). IDEMPOTENCY_KEY_CONFLICT — key já usada para uma viagem diferente do enviado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    BoardingController_reminder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envelope { data, meta } com data null ou { tripId, remindedAt }. A viagem ativa é resolvida pelo domínio trip ANTES do boarding — aluno sem viagem de retorno ativa já recebe data null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PendingReminderResponseDto"] | null;
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN — role STUDENT exigida (o lembrete é do aluno). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    BoardingController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream `text/event-stream` — uma mensagem por evento, com `event:` carregando o tipo e `data:` o payload JSON (oneOf dos três schemas). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["BoardingNotReturningEventDto"] | components["schemas"]["BoardingAbsenceCancelledEventDto"] | components["schemas"]["BoardingCheckinReminderEventDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN — role DRIVER exigida; somente o motorista atribuído à rota abre o stream daquela viagem. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — motorista autenticado sem viagem ativa (inexistente, encerrada ou de outra empresa). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TrackingController_ingestLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationIngestRequestDto"];
            };
        };
        responses: {
            /** @description Posição recebida — ack com o instante de recebimento do servidor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LocationIngestResponseDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description VALIDATION_ERROR — body malformado (tripId ausente ou não é UUID, coordenadas ausentes ou não numéricas, capturedAt não ISO 8601). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description DRIVER_NOT_ON_TRIP — motorista autenticado não é o atribuído à viagem (espelho do STUDENT_NOT_ON_TRIP do boarding). FORBIDDEN — role DRIVER exigida: somente o motorista transmite GPS. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa (posição só é aceita em viagem ativa). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TrackingController_activeTrackingTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envelope { data, meta } com data null (sem viagem ativa na rota do aluno) ou { tripId, type }. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ActiveTrackingTripDto"] | null;
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description FORBIDDEN — role STUDENT exigida: o acompanhamento é do aluno (sem viagem é { data: null }, não 403). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TrackingController_lastKnownLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da viagem */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Último ponto conhecido da viagem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LastKnownLocationDto"];
                        meta: {
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description VALIDATION_ERROR — id da viagem ausente ou não é UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ON_TRIP — aluno não vinculado à rota da viagem (mesmo código/semântica do boarding). FORBIDDEN — role STUDENT exigida: o acompanhamento é do aluno. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description NO_LOCATION_AVAILABLE — nenhuma posição armazenada para a viagem (cache vazio ou TTL expirado). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TrackingController_tripLocationStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da viagem */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream `text/event-stream` — uma mensagem por posição publicada, com `event:` carregando `location.updated` e `data:` o payload JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LocationUpdatedEventDto"];
                };
            };
            /** @description VALIDATION_ERROR — id da viagem ausente ou não é UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STUDENT_NOT_ON_TRIP — aluno não vinculado à rota da viagem (mesmo código/semântica do boarding). FORBIDDEN — role STUDENT exigida: o acompanhamento é do aluno. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description TRIP_NOT_ACTIVE — viagem inexistente, de outra empresa ou não ativa. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
